#!/bin/tcsh -f

# CMSC 216, Spring 2022, Project #10
# Public test 5 (public5)
#
# Tests running the second program to compute catalan(3).
#
# (c) Larry Herman, 2022.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

spim -file prog3.s < public5.inputdata | tail -n +2
