#!/bin/tcsh -f

# CMSC 216, Spring 2022, Project #10
# Public test 7 (public7)
#
# Tests running the third program to compute catalan(0).
#
# (c) Larry Herman, 2022.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

spim -file prog3.s < public7.inputdata | tail -n +2
