#!/bin/tcsh -f

# CMSC 216, Spring 2022, Project #10
# Public test 2 (public2)
#
# Tests running the first program to compute reverse_digits(216).
#
# (c) Larry Herman, 2022.  You are allowed to use this code yourself, but
# not to provide it to anyone else.

spim -file prog1.s < public2.inputdata | tail -n +2
